# Generated by Django 5.0.1 on 2024-04-24 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0014_profile_facebook_url_profile_instagram_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_added']},
        ),
    ]
